// <auto-generated />
using System;
using Fretefy.Test.Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fretefy.Test.Infra.Fretefy.Test.Infra.Data.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250605104644_NomeDescritivoDaSuaMigration")]
    partial class NomeDescritivoDaSuaMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e9db7f0-e40a-4e68-9b9a-e7efc3ad60c4"),
                            Nome = "Rio Branco",
                            UF = "AC"
                        },
                        new
                        {
                            Id = new Guid("1c846b6d-d207-48b3-b70d-e7ac2bc9f101"),
                            Nome = "Maceió",
                            UF = "AL"
                        },
                        new
                        {
                            Id = new Guid("5f402477-3a90-421f-8cde-6d982f1c872d"),
                            Nome = "Macapá",
                            UF = "AP"
                        },
                        new
                        {
                            Id = new Guid("83db2c9e-d62a-48ad-b07f-11f89d504951"),
                            Nome = "Manaus",
                            UF = "AM"
                        },
                        new
                        {
                            Id = new Guid("0c97466d-51b3-4097-93f9-41b7fbc5f8a3"),
                            Nome = "Salvador",
                            UF = "BA"
                        },
                        new
                        {
                            Id = new Guid("b51a6b2d-4123-4632-b2c5-87f57d7480db"),
                            Nome = "Fortaleza",
                            UF = " CE"
                        },
                        new
                        {
                            Id = new Guid("09db72f5-ef75-4785-bf59-b5103063acdd"),
                            Nome = "Brasília",
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("42c606b9-2958-4961-a3a6-92ccfc3b7078"),
                            Nome = "Vitória",
                            UF = "ES"
                        },
                        new
                        {
                            Id = new Guid("8db0d3f9-121b-4f63-8d84-27a2a8dfdfdd"),
                            Nome = "Goiânia",
                            UF = "GO"
                        },
                        new
                        {
                            Id = new Guid("b4abf477-e221-4017-9b62-caa52b24dfb4"),
                            Nome = "São Luís",
                            UF = "MA"
                        },
                        new
                        {
                            Id = new Guid("72a2cb2d-fc50-48e4-a6e9-8599082d2b85"),
                            Nome = "Cuiabá",
                            UF = "MT"
                        },
                        new
                        {
                            Id = new Guid("51b78b97-fb88-4661-bd68-df20c02ae283"),
                            Nome = "Campo Grande",
                            UF = "MS"
                        },
                        new
                        {
                            Id = new Guid("3fbe0e9c-4cc9-4643-9ff1-bc57a9bcb762"),
                            Nome = "Belo Horizonte",
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("17e01bc5-9f73-4531-9074-eefb7b8d458d"),
                            Nome = "Belém",
                            UF = "PA"
                        },
                        new
                        {
                            Id = new Guid("6a2b041f-f924-468d-8635-63c62358d435"),
                            Nome = "João Pessoa",
                            UF = "PB"
                        },
                        new
                        {
                            Id = new Guid("b07bb4e0-6a90-4f2f-86d7-80b198582dc0"),
                            Nome = "Curitiba",
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("1ccbd6ae-0e58-4f91-bb02-dad31c8201b1"),
                            Nome = "Recife",
                            UF = "PE"
                        },
                        new
                        {
                            Id = new Guid("332ce25e-47f1-44d9-99d5-1ae913b0ac88"),
                            Nome = "Teresina",
                            UF = "PI"
                        },
                        new
                        {
                            Id = new Guid("dd99bc63-4772-4ec0-a9b2-4c345f4d7de5"),
                            Nome = "Rio de Janeiro",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("4d545f9e-1ff4-471a-bbfe-7be8e5b522bc"),
                            Nome = "Natal",
                            UF = "RN"
                        },
                        new
                        {
                            Id = new Guid("f8f3adf6-2c5e-4f2e-9b7e-9fa745672d85"),
                            Nome = "Porto Alegre",
                            UF = "RS"
                        },
                        new
                        {
                            Id = new Guid("340ebc11-fc7c-49b2-9b4c-00b6f89c9990"),
                            Nome = "Porto Velho",
                            UF = "RO"
                        },
                        new
                        {
                            Id = new Guid("805855e0-86d6-4f79-bc4e-c3c71b3d827a"),
                            Nome = "Boa Vista",
                            UF = "RR"
                        },
                        new
                        {
                            Id = new Guid("2eecb465-7f31-4592-81f3-8a5b8fa5b254"),
                            Nome = "Florianópolis",
                            UF = "SC"
                        },
                        new
                        {
                            Id = new Guid("af1c7b8e-d3d8-4d58-b8b6-18fdaab71a92"),
                            Nome = "São Paulo",
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("d72b501a-34f5-47b2-9a5f-b21b3a3daaa5"),
                            Nome = "Aracaju",
                            UF = "SE"
                        },
                        new
                        {
                            Id = new Guid("7c11f1d4-34bc-4260-a109-b1d7ac1bc129"),
                            Nome = "Palmas",
                            UF = "TO"
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Regiao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0f7d0d5-4b6f-4b08-93b2-e49a3f214735"),
                            Ativo = true,
                            Nome = "Norte"
                        },
                        new
                        {
                            Id = new Guid("5d7df2c0-1f33-4bb0-8032-2a6d8f6dcbf9"),
                            Ativo = true,
                            Nome = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("9e9c4b2f-9c74-438d-98b0-0220193925c1"),
                            Ativo = true,
                            Nome = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("4e2736f3-017f-4c6b-81b8-9ba4ed1e37cd"),
                            Ativo = false,
                            Nome = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("b0c7d3f3-c1ab-4a2d-9338-c88cc51080c7"),
                            Ativo = false,
                            Nome = "Sul"
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.RegiaoCidade", b =>
                {
                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("TEXT");

                    b.HasKey("RegiaoId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.ToTable("RegiaoCidade");

                    b.HasData(
                        new
                        {
                            RegiaoId = new Guid("f0f7d0d5-4b6f-4b08-93b2-e49a3f214735"),
                            CidadeId = new Guid("8e9db7f0-e40a-4e68-9b9a-e7efc3ad60c4")
                        },
                        new
                        {
                            RegiaoId = new Guid("f0f7d0d5-4b6f-4b08-93b2-e49a3f214735"),
                            CidadeId = new Guid("1c846b6d-d207-48b3-b70d-e7ac2bc9f101")
                        },
                        new
                        {
                            RegiaoId = new Guid("f0f7d0d5-4b6f-4b08-93b2-e49a3f214735"),
                            CidadeId = new Guid("5f402477-3a90-421f-8cde-6d982f1c872d")
                        },
                        new
                        {
                            RegiaoId = new Guid("f0f7d0d5-4b6f-4b08-93b2-e49a3f214735"),
                            CidadeId = new Guid("0c97466d-51b3-4097-93f9-41b7fbc5f8a3")
                        },
                        new
                        {
                            RegiaoId = new Guid("4e2736f3-017f-4c6b-81b8-9ba4ed1e37cd"),
                            CidadeId = new Guid("dd99bc63-4772-4ec0-a9b2-4c345f4d7de5")
                        },
                        new
                        {
                            RegiaoId = new Guid("4e2736f3-017f-4c6b-81b8-9ba4ed1e37cd"),
                            CidadeId = new Guid("f8f3adf6-2c5e-4f2e-9b7e-9fa745672d85")
                        },
                        new
                        {
                            RegiaoId = new Guid("4e2736f3-017f-4c6b-81b8-9ba4ed1e37cd"),
                            CidadeId = new Guid("805855e0-86d6-4f79-bc4e-c3c71b3d827a")
                        },
                        new
                        {
                            RegiaoId = new Guid("5d7df2c0-1f33-4bb0-8032-2a6d8f6dcbf9"),
                            CidadeId = new Guid("1ccbd6ae-0e58-4f91-bb02-dad31c8201b1")
                        },
                        new
                        {
                            RegiaoId = new Guid("9e9c4b2f-9c74-438d-98b0-0220193925c1"),
                            CidadeId = new Guid("dd99bc63-4772-4ec0-a9b2-4c345f4d7de5")
                        },
                        new
                        {
                            RegiaoId = new Guid("b0c7d3f3-c1ab-4a2d-9338-c88cc51080c7"),
                            CidadeId = new Guid("af1c7b8e-d3d8-4d58-b8b6-18fdaab71a92")
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.RegiaoCidade", b =>
                {
                    b.HasOne("Fretefy.Test.Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fretefy.Test.Domain.Entities.Regiao", "Regiao")
                        .WithMany("RegiaoCidades")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("RegiaoCidades");
                });
#pragma warning restore 612, 618
        }
    }
}
